-- NexShop Gaming News production schema.
-- Aman ditempel ulang di Supabase SQL Editor. Backend memakai SUPABASE_SERVICE_KEY;
-- RLS di bawah ini mencegah akses langsung dari browser ke tabel ini.

create table if not exists public.gaming_news (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    summary text not null,
    source varchar(80) not null,
    source_url text not null,
    canonical_url text not null,
    image_url text not null,
    publisher_logo_url text not null default '',
    category varchar(80) not null default 'Gaming',
    published_at timestamptz not null,
    is_active boolean not null default false,
    is_hidden boolean not null default false,
    is_pinned boolean not null default false,
    is_featured boolean not null default false,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint gaming_news_source_url_key unique (source_url),
    constraint gaming_news_sort_order_check check (sort_order between 0 and 100000),
    constraint gaming_news_title_not_blank check (length(btrim(title)) > 0),
    constraint gaming_news_summary_word_count check (cardinality(regexp_split_to_array(btrim(summary), '\s+')) between 80 and 150)
);

alter table public.gaming_news
    alter column title type varchar(255),
    alter column summary type text,
    alter column source type varchar(80),
    add column if not exists canonical_url text,
    add column if not exists publisher_logo_url text not null default '',
    add column if not exists category varchar(80) not null default 'Gaming',
    add column if not exists is_hidden boolean not null default false,
    add column if not exists is_pinned boolean not null default false,
    add column if not exists is_featured boolean not null default false,
    add column if not exists sort_order integer not null default 0,
    add column if not exists created_at timestamptz not null default now(),
    add column if not exists updated_at timestamptz not null default now();

-- Baris lama mendapat canonical URL dan kategori yang aman. Ringkasan lama tidak
-- dipaksa menjadi 80 kata agar migration tidak merusak arsip yang sudah ada.
update public.gaming_news
set canonical_url = source_url
where canonical_url is null or btrim(canonical_url) = '';

update public.gaming_news
set category = 'Gaming'
where category is null or btrim(category) = '';

alter table public.gaming_news
    alter column canonical_url set not null,
    alter column publisher_logo_url set default '',
    alter column category set default 'Gaming',
    alter column is_active set default false;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'gaming_news_sort_order_check') then
        alter table public.gaming_news
            add constraint gaming_news_sort_order_check check (sort_order between 0 and 100000) not valid;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'gaming_news_title_not_blank') then
        alter table public.gaming_news
            add constraint gaming_news_title_not_blank check (length(btrim(title)) > 0) not valid;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'gaming_news_summary_word_count') then
        alter table public.gaming_news
            add constraint gaming_news_summary_word_count check (cardinality(regexp_split_to_array(btrim(summary), '\s+')) between 80 and 150) not valid;
    end if;
end $$;

-- source_url adalah unique key utama. canonical_url tetap diindeks (bukan UNIQUE)
-- agar arsip URL lama yang ternyata mengarah ke canonical yang sama tidak hilang.
create index if not exists gaming_news_canonical_url_idx
    on public.gaming_news (canonical_url);
create index if not exists gaming_news_public_idx
    on public.gaming_news (is_active, is_hidden, is_pinned desc, is_featured desc, sort_order asc, published_at desc);
create index if not exists gaming_news_admin_idx
    on public.gaming_news (published_at desc, source, category);

create or replace function public.set_gaming_news_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_gaming_news_updated_at on public.gaming_news;
create trigger set_gaming_news_updated_at
before update on public.gaming_news
for each row execute function public.set_gaming_news_updated_at();

alter table public.gaming_news enable row level security;
revoke all on table public.gaming_news from anon, authenticated;
grant select, insert, update, delete on table public.gaming_news to service_role;
grant usage, select on sequence public.gaming_news_id_seq to service_role;
