-- ============================================================================
-- Migration: topup_ratings
-- Jalankan ini manual di Supabase SQL Editor (Project > SQL Editor > New query).
-- Saya (Claude) tidak punya akses/kredensial ke database Supabase kamu, jadi
-- tabel ini TIDAK otomatis dibuat -- perlu dijalankan manual sebelum fitur
-- "rating topup" di backend/frontend bisa berfungsi (endpoint-nya akan error
-- 42P01 "relation does not exist" sampai migration ini dijalankan).
--
-- Mirroring struktur `order_ratings` yang sudah ada (dipakai ratingController.js),
-- tapi untuk topup_orders (bukan orders), karena order_id di order_ratings
-- ber-FK ke tabel `orders` -- topup_orders punya ruang ID sendiri ("TP...")
-- yang tidak bisa dicampur ke FK yang sama tanpa mengubah constraint tabel
-- lama (berisiko ke data existing). Tabel terpisah = lebih aman.
--
-- `display_name` (baru, tidak ada di order_ratings): checkout topup TIDAK
-- pernah mengumpulkan nama pembeli (cuma tujuan/Player ID, email, no. HP --
-- lihat topupController.js exports.create), jadi tidak ada nama asli yang
-- bisa dipakai buat testimoni publik seperti order_ratings pakai
-- orders.recipient_name. Kolom ini OPSIONAL, diisi manual oleh pembeli saat
-- submit rating kalau mereka mau testimoninya tampil dengan nama (kalau
-- dikosongkan, ditampilkan sebagai "Pembeli Topup" di frontend).
-- ============================================================================

create table if not exists public.topup_ratings (
    id          bigint generated by default as identity primary key,
    order_id    text not null references public.topup_orders(id) on delete cascade,
    user_id     bigint references public.users(id) on delete set null,
    score       smallint not null check (score between 1 and 5),
    comment     text,
    display_name text,
    created_at  timestamptz not null default now(),

    -- Satu topup order cuma boleh dirating sekali -- konsisten dengan
    -- order_ratings (submitRating menangani error code 23505 unique_violation
    -- sebagai "Rating untuk order ini sudah pernah dikirim").
    constraint topup_ratings_order_id_key unique (order_id)
);

create index if not exists idx_topup_ratings_order_id on public.topup_ratings(order_id);
create index if not exists idx_topup_ratings_score on public.topup_ratings(score);

-- Kalau RLS aktif di project Supabase kamu (default untuk project baru),
-- service role key yang dipakai backend (SUPABASE_SERVICE_KEY di .env)
-- otomatis bypass RLS, jadi tabel ini akan langsung bisa dipakai backend
-- tanpa policy tambahan -- sama seperti order_ratings yang sudah ada.
-- Aktifkan baris di bawah SAJA kalau kamu juga berencana query tabel ini
-- langsung dari client-side dengan anon/public key (saat ini backend NexShop
-- tidak melakukan itu untuk rating, semua lewat endpoint Express).
-- alter table public.topup_ratings enable row level security;
