-- ============================================================================
-- Migration: custom_testimonials
-- Jalankan ini manual di Supabase SQL Editor (Project > SQL Editor > New query).
--
-- FEATURE: Testimoni kustom yang bisa diatur penuh dari Admin Dashboard --
-- nama, rating bintang, foto profil, dan produk yang "dibeli" semuanya
-- diisi manual oleh admin (bukan hasil rating asli dari pembeli). Ini
-- terpisah dari order_ratings/topup_ratings (rating asli) supaya data asli
-- tidak pernah tercampur/tertimpa oleh testimoni yang dibuat manual.
--
-- Endpoint publik "Apa Kata Mereka" (getPublicTestimonials di
-- ratingController.js) menggabungkan baris is_active=true dari tabel ini
-- dengan rating asli yang eligible (score>=4 & ada komentar).
-- ============================================================================

create table if not exists public.custom_testimonials (
    id            bigint generated by default as identity primary key,
    name          text not null,
    avatar_url    text,
    score         smallint not null check (score between 1 and 5),
    product_name  text,
    comment       text not null,
    is_active     boolean not null default true,
    display_order integer not null default 0,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now()
);

create index if not exists idx_custom_testimonials_active on public.custom_testimonials(is_active);
create index if not exists idx_custom_testimonials_order on public.custom_testimonials(display_order);

-- Kalau RLS aktif di project Supabase kamu (default untuk project baru),
-- service role key yang dipakai backend otomatis bypass RLS, jadi tabel ini
-- akan langsung bisa dipakai backend tanpa policy tambahan.
-- alter table public.custom_testimonials enable row level security;
