-- Migration 022: kontak WhatsApp kanonis dari akun user terverifikasi.
--
-- Kontak hanya dibuat dari nomor yang sudah dibuktikan lewat OTP. Tabel ini
-- tidak menyimpan token gateway atau credential apa pun.

CREATE TABLE IF NOT EXISTS public.whatsapp_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    display_name TEXT NOT NULL,
    phone_e164 TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'verified_user',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT whatsapp_contacts_user_id_key UNIQUE (user_id),
    CONSTRAINT whatsapp_contacts_phone_e164_key UNIQUE (phone_e164),
    CONSTRAINT whatsapp_contacts_source_check CHECK (source IN ('verified_user', 'admin_sync'))
);

CREATE INDEX IF NOT EXISTS idx_whatsapp_contacts_display_name
    ON public.whatsapp_contacts (lower(display_name));

CREATE INDEX IF NOT EXISTS idx_whatsapp_contacts_updated_at
    ON public.whatsapp_contacts (updated_at DESC);

COMMENT ON TABLE public.whatsapp_contacts IS
    'Kontak WhatsApp dari akun NexShop dengan nomor yang telah diverifikasi OTP.';
COMMENT ON COLUMN public.whatsapp_contacts.phone_e164 IS
    'Nomor WhatsApp kanonis dalam format E.164 (+628...).';
