const fs = require("fs");
const path = require("path");
const root = path.resolve(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8").replace(/\r\n/g, "\n");
const css = read("nexshop-frontend/reseller.css");
const portalCss = read("nexshop-frontend/portal-reseller.css");
const html = read("nexshop-frontend/reseller.html");
const mobileStart = css.indexOf("@media (max-width: 680px)");
const mobileEnd = css.indexOf("@media (prefers-reduced-motion", mobileStart);
const mobile = css.slice(mobileStart, mobileEnd);
const assert = (condition, message) => { if (!condition) throw new Error(message); };

const mobileContract = css.slice(css.lastIndexOf("@media (max-width: 680px)"));
assert(/\.rs-showcase-grid[\s\S]*?grid-template-columns:\s*1fr/.test(mobileContract), "mobile reseller showcase must use a dedicated one-column layout");
assert(!/grid-auto-flow:\s*column|grid-auto-columns:\s*minmax\(86%/.test(mobileContract), "mobile reseller showcase must not be a horizontal desktop-like rail");
assert(/\.rs-showcase-card[\s\S]*?min-height:\s*auto/.test(mobileContract), "mobile reseller cards must use content-driven height");
assert(/\.rs-story-transactions[\s\S]*?min-height:\s*252px/.test(mobileContract), "mobile transactions visual must have a compact dedicated frame");
assert(/\.rs-story-bills[\s\S]*?min-height:\s*270px/.test(mobileContract), "mobile bills visual must have a compact dedicated frame");
assert(/\.rs-story-catalog[\s\S]*?min-height:\s*230px/.test(mobileContract), "mobile catalog visual must have a compact dedicated frame");
assert(/\.rs-story-pricing[\s\S]*?min-height:\s*230px/.test(mobileContract), "mobile pricing visual must have a compact dedicated frame");
assert(/\.rs-story-wallet[\s\S]*?min-height:\s*252px/.test(mobileContract), "mobile wallet visual must have a compact dedicated frame");
assert(/\.rs-story-api[\s\S]*?min-height:\s*264px/.test(mobileContract), "mobile API visual must have a compact dedicated frame");
assert(/rs-tier-card-silver[\s\S]*#(?:e2e8f0|c0c0c0|94a3b8|f3f5f7)/i.test(css), "Silver must retain a cool metallic token");
assert(/rs-tier-card-platinum[\s\S]*#(?:f4efe6|e5e4e2|b7a98d|a7b0bb)/i.test(css), "Platinum must use a pearl token");
assert(/tv-tier-silver[\s\S]*#(?:e2e8f0|c0c0c0|94a3b8)/i.test(portalCss), "Portal Silver must use the cool metallic token");
assert(/tv-tier-platinum[\s\S]*#(?:f4efe6|e5e4e2|b7a98d|a7b0bb)/i.test(portalCss), "Portal Platinum must use the pearl token");
assert(/style\.css\?v=20260904-mobile-card-avatar-template-2/.test(html), "reseller page must use the current shared style cache-buster");
console.log("sim106_reseller_mobile_card_variant: PASS");
