const fs = require("fs");
const path = require("path");
const root = path.resolve(__dirname, "..");
const css = fs.readFileSync(path.join(root, "nexshop-frontend/reseller.css"), "utf8").replace(/\r\n/g, "\n");
const html = fs.readFileSync(path.join(root, "nexshop-frontend/reseller.html"), "utf8").replace(/\r\n/g, "\n");
const assert = (condition, message) => { if (!condition) throw new Error(message); };
assert(/class="rs-flow-svg rs-api-flow-svg"/.test(html), "API route must use an explicit SVG flow layer");
assert(/initResponsiveConnectionFlows[\s\S]*?\.rs-api-node-shop[\s\S]*?\.rs-api-node-api[\s\S]*?\.rs-api-node-biller[\s\S]*?\.rs-api-node-hook/.test(fs.readFileSync(path.join(root, "nexshop-frontend/reseller.js"), "utf8")), "API flow must be generated from node geometry");
const connectionMotion = (css.match(/@keyframes\\s+(?:rs-network-pulse|rs-wallet-flow|rs-api-pulse|rs-universe-route-pulse)\\s*\\{[\\s\\S]*?\\n\\}/g) || []).join("\\n");
assert(!connectionMotion.includes("translateX(") || !connectionMotion.includes("px"), "API connection visuals must not use fixed-pixel particle travel");
assert(/rs-api-route-line-1[\s\S]*rs-api-route-line-2[\s\S]*rs-api-route-line-3/.test(html), "API route must remain ordered left-to-right");
console.log("sim107_reseller_api_motion_direction: PASS");
